# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: prawn_rails 0.0.12 ruby lib

Gem::Specification.new do |s|
  s.name = "prawn_rails".freeze
  s.version = "0.0.12"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Walton Hoops".freeze]
  s.date = "2021-07-07"
  s.description = "The prawn_rails gem provides a Prawn based view engine for creating PDFs with rails.".freeze
  s.email = "me@waltonhoops.com".freeze
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "init.rb",
    "lib/prawn_rails.rb",
    "prawn_rails.gemspec",
    "rails/init.rb"
  ]
  s.homepage = "http://github.com/Whoops/prawn-rails".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.2.21".freeze
  s.summary = "Integrates Prawn into Rails in a natural way".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_runtime_dependency(%q<railties>.freeze, [">= 3.0.0"])
    s.add_runtime_dependency(%q<prawn>.freeze, [">= 0.11.1"])
  else
    s.add_dependency(%q<railties>.freeze, [">= 3.0.0"])
    s.add_dependency(%q<prawn>.freeze, [">= 0.11.1"])
  end
end

